name: document-update

# GitHub Actions Workflows are automatically triggered by GitHub events
on: 
  pull_request:
    types: [assigned, opened, synchronize, reopened]
jobs:
  document_update_reminder:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
      GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}

    steps:
      - uses: actions/checkout@v2
      #- uses: actions/hello-world-javascript-action@v1
      #  id: hello-action
      #- run: echo ${{steps.hello-action.outputs.time}}
      - uses: sagarjhaa/Documinder@main
        id: document-reminder
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}  
      - run: "echo ${{ github.event.inputs.content }}!" 
    #  - uses: actions/setup-node@v1
    #  - run: npm install -g @actions/core @actions/github
    #  - uses: ./.github/actions
